export const connectionsPlans = [
  {
    'connectionId': 'CONN001',
    'connectionName': 'Dial-Up Connection',
    'slug': 'dial-up-connection',
    'plans': [
      {
        'planId': 'PLAN001D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up 10 Hrour Plan',
        'planDetails': '10 Hours',
        'planType': 'Hourly',
        'planPrice': 50,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': '10 Hours Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN002D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up 30 Hours Plan',
        'planDetails': '30 Hours',
        'planType': 'Hourly',
        'planPrice': 130,
        'planValidity': '3 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': '30 Hours Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN003D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up 60 Hours Plan',
        'planDetails': '60 Hours',
        'planType': 'Hourly',
        'planPrice': 260,
        'planValidity': '6 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': '60 Hours Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN004D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up Unlimited 28Kbps Monthly',
        'planDetails': 'Monthly',
        'planType': 'Unlimited',
        'planPrice': 75,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 28Kbps Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN005D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up Unlimited 28Kbps Quarterly',
        'planDetails': 'Quarterly',
        'planType': 'Unlimited',
        'planPrice': 150,
        'planValidity': '3 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 28Kbps Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN006D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up Unlimited 56Kbps Monthly',
        'planDetails': 'Monthly',
        'planType': 'Unlimited',
        'planPrice': 100,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 56Kbps Dial-Up Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN007D',
        'connectionId': 'CONN001',
        'planName': 'Dial-Up Unlimited 56Kbps Quarterly',
        'planDetails': 'Quarterly',
        'planType': 'Unlimited',
        'planPrice': 180,
        'planValidity': '3 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 56Kbps Dial-Up Plan',
        'planIsActive': true
      }
    ]
  },
  {
    'connectionId': 'CONN002',
    'connectionName': 'Broad Band Connection',
    'slug': 'broadband-connection',
    'plans': [
      {
        'planId': 'PLAN008B',
        'connectionId': 'CONN002',
        'planName': 'Broadband 30 Hours Plan',
        'planDetails': '30 Hours',
        'planType': 'Hourly',
        'planPrice': 175,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': '30 Hours Broadband Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN009B',
        'connectionId': 'CONN002',
        'planName': 'Broadband 60 Hours Plan',
        'planDetails': '60 Hours',
        'planType': 'Hourly',
        'planPrice': 315,
        'planValidity': '6 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': '60 Hours Broadband Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN010B',
        'connectionId': 'CONN002',
        'planName': 'Broadband Unlimited 64Kbps Monthly',
        'planDetails': 'Monthly',
        'planType': 'Unlimited',
        'planPrice': 225,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 64Kbps Broadband Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN011B',
        'connectionId': 'CONN002',
        'planName': 'Broadband Unlimited 64Kbps Quarterly',
        'planDetails': 'Quarterly',
        'planType': 'Unlimited',
        'planPrice': 400,
        'planValidity': '3 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 64Kbps Broadband Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN012B',
        'connectionId': 'CONN002',
        'planName': 'Broadband Unlimited 128Kbps Monthly',
        'planDetails': 'Monthly',
        'planType': 'Unlimited',
        'planPrice': 350,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 128Kbps Broadband Plan',
        'planIsActive': true
      },
      {
        'planId': 'PLAN013B',
        'connectionId': 'CONN002',
        'planName': 'Broadband Unlimited 128Kbps Quarterly',
        'planDetails': 'Quarterly',
        'planType': 'Unlimited',
        'planPrice': 445,
        'planValidity': '3 Months',
        'planLocalCallCharge': 0,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited 128Kbps Broadband Plan',
        'planIsActive': true
      }
    ]
  },
  {
    'connectionId': 'CONN003',
    'connectionName': 'LandLine Connection',
    'slug': 'landline-connection',
    'plans': [
      {
        'planId': 'PLAN014T',
        'connectionId': 'CONN003',
        'planName': 'LandLine Unlimited Rental',
        'planDetails': 'Unlimited Rental',
        'planType': 'Local',
        'planPrice': 75,
        'planValidity': '1 Year',
        'planLocalCallCharge': 0.55,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Unlimited Local Calls with Rental',
        'planIsActive': true
      },
      {
        'planId': 'PLAN015T',
        'connectionId': 'CONN003',
        'planName': 'LandLine Monthly Rental',
        'planDetails': 'Monthly Rental',
        'planType': 'Local',
        'planPrice': 35,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0.75,
        'planSTDCallCharge': 0,
        'planMessagingCharge': 0,
        'planDescription': 'Monthly Local Calls with Rental',
        'planIsActive': true
      },
      {
        'planId': 'PLAN016T',
        'connectionId': 'CONN003',
        'planName': 'LandLine STD Monthly Rental',
        'planDetails': 'Monthly Rental',
        'planType': 'STD',
        'planPrice': 125,
        'planValidity': '1 Month',
        'planLocalCallCharge': 0.7,
        'planSTDCallCharge': 2.25,
        'planMessagingCharge': 1,
        'planDescription': 'Monthly STD Plan with Messaging',
        'planIsActive': true
      },
      {
        'planId': 'PLAN017T',
        'connectionId': 'CONN003',
        'planName': 'LandLine STD Half-Yearly Rental',
        'planDetails': 'Half-Yearly Rental',
        'planType': 'STD',
        'planPrice': 420,
        'planValidity': '6 Months',
        'planLocalCallCharge': 0.6,
        'planSTDCallCharge': 2,
        'planMessagingCharge': 1.15,
        'planDescription': 'Half-Yearly STD Plan with Messaging',
        'planIsActive': true
      },
      {
        'planId': 'PLAN018T',
        'connectionId': 'CONN003',
        'planName': 'LandLine STD Yearly Rental',
        'planDetails': 'Yearly Rental',
        'planType': 'STD',
        'planPrice': 800,
        'planValidity': '1 Year',
        'planLocalCallCharge': 0.6,
        'planSTDCallCharge': 1.75,
        'planMessagingCharge': 1.25,
        'planDescription': 'Yearly STD Plan with Messaging',
        'planIsActive': true
      }
    ]
  }
]